name: 'tt04' # used for university orders & docs
start_date: '2023-06-14'

filler_project: https://github.com/TinyTapeout/tt04-factory-test # used by Orders when updating list of real projects
extra_projects: extra_projects.yaml

project_dir: 'projects'
test_project_dir: 'test_projects'

num_projects: 32
