name: 'Tiny Tapeout Viewer Action'
description: 'This action create a 3D model of your Tiny Tapeout project'
branding:
  color: purple
  icon: eye

inputs:
  pdk_name:
    description: 'PDK Name (e.g. sky130)'
    default: 'sky130'
  pdk_version:
    description: 'PDK Version (e.g. 2023.05.27)'
    required: true
  pdk_root:
    description: 'PDK Directory (e.g. ~/.volare)'
    default: '~/.volare'

runs:
  using: 'composite'
  steps:
    - name: Cache
      id: cache-pdk
      uses: actions/cache@v3
      with:
        path: ~/.cache
        key: ${{ runner.os }}-pdk-${{ inputs.pdk_name }}-${{ inputs.pdk_version }}

    - name: Install Sky130 PDK
      shell: bash
      if: steps.cache-primes.outputs.cache-hit != 'true'
      run: |
        pip3 install volare
        volare enable --pdk "${{ inputs.pdk_name }}" "${{ inputs.pdk_version }}"
      env:
        SKY130_PDK_VERSION: ${{ inputs.pdk_version }}
